# Form implementation generated from reading ui file 'homework2.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 50, 151, 51))
        self.label.setObjectName("label")
        # self.label.hide()

        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 130, 151, 51))
        self.label_2.setObjectName("label_2")
        # self.label_2.hide()

        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(240, 50, 151, 51))
        self.label_3.setObjectName("label_3")
        # self.label_3.hide()

        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(370, 90, 101, 71))
        self.pushButton.setObjectName("pushButton")
        # self.pushButton.hide()

        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(490, 10, 281, 231))
        self.label_4.setObjectName("label_4")
        # self.label_4.hide()

        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 100, 121, 31))
        self.lineEdit.setObjectName("lineEdit")
        # self.lineEdit.hide()

        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(110, 180, 121, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        # self.lineEdit_2.hide()

        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(240, 100, 121, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        # self.lineEdit_3.hide()

        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 230, 151, 51))
        self.label_5.setObjectName("label_5")
        # self.label_5.hide()

        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(10, 270, 121, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        # self.lineEdit_4.hide()

        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(150, 250, 101, 71))
        self.pushButton_2.setObjectName("pushButton_2")
        # self.pushButton_2.hide()

        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(270, 170, 281, 231))
        self.label_6.setObjectName("label_6")
        # self.label_6.hide()

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(parent=MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.action = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("piramida.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.action.setIcon(icon)
        self.action.setObjectName("action")
        self.action_2 = QtGui.QAction(parent=MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("parall.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.action_2.setIcon(icon1)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtGui.QAction(parent=MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("shar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.action_3.setIcon(icon2)
        self.action_3.setObjectName("action_3")
        self.toolBar.addAction(self.action)
        self.toolBar.addAction(self.action_2)
        self.toolBar.addAction(self.action_3)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.hide_parall()
        self.hide_pir()

        self.action_2.triggered.connect(self.parall_text)
        self.action.triggered.connect(self.pir_text)
        self.pushButton.clicked.connect(self.result)

    def result(self):
        self.label_4.setText(str(int(self.lineEdit.text()) * int(self.lineEdit_2.text()) * int(self.lineEdit_3.text())))

    def hide_parall(self):
        self.label.hide()
        self.label_2.hide()
        self.label_3.hide()
        self.pushButton.hide()
        self.label_4.hide()
        self.lineEdit.hide()
        self.lineEdit_2.hide()
        self.lineEdit_3.hide()
        self.pushButton.hide()

    def show_parall(self):
        self.hide_parall()
        self.label.show()
        self.label_2.show()
        self.label_3.show()
        self.label_4.show()
        self.lineEdit.show()
        self.lineEdit_2.show()
        self.lineEdit_3.show()
        self.pushButton.show()

    def hide_pir(self):
        self.label_5.hide()
        self.lineEdit_4.hide()
        self.pushButton_2.hide()
        self.label_6.hide()

    def shor_pir(self):
        self.label_5.show()
        self.lineEdit_4.show()
        self.pushButton_2.show()
        self.label_6.show()

    def parall_text(self):
        self.show_parall()
        self.hide_pir()

    def pir_text(self):
        self.hide_parall()
        self.shor_pir()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Введите сторону А"))
        self.label_2.setText(_translate("MainWindow", "Введите сторону B"))
        self.label_3.setText(_translate("MainWindow", "Введите сторону С"))
        self.pushButton.setText(_translate("MainWindow", "="))
        self.label_4.setText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "Введите радиус"))
        self.pushButton_2.setText(_translate("MainWindow", "="))
        self.label_6.setText(_translate("MainWindow", "TextLabel"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action.setText(_translate("MainWindow", "Пирамида"))
        self.action.setToolTip(_translate("MainWindow", "Пирамида"))
        self.action_2.setText(_translate("MainWindow", "Параллелограмм"))
        self.action_2.setToolTip(_translate("MainWindow", "Параллелограмм"))
        self.action_3.setText(_translate("MainWindow", "Шар"))
        self.action_3.setToolTip(_translate("MainWindow", "Шар"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
